baseURL = 'https://aquarite.info/'
languageCode = 'ja-jp'
title = 'Hello, (forgotten) world ☂'
author = 'Mei Akizuru'
theme = 'blackburn'
copyright = "&copy; 2021 Mei Akizuru. All rights reserved."
canonifyurls = true
paginate = 10
hasCJKLanguage = true
summaryLength = 140

ignoreErrors = ["error-remote-getjson"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'dracula'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  brand = "aquarite.info"
  dateFormat = "02 Jan 2006, 15:04"
  disable_mathjax = true
  goatcounterAnalytics = "aquarite"

[permalinks]
  posts = '/blog/:year/:month/:slug'

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

[social]
  twitter = "maytheplic"
  github = "mayth"
  steam = "maythorzy"
